server:
  port: 8095
spring:
  datasource:
    url: jdbc:h2:mem:javatos
    driver-class-name: org.h2.Driver
    username: root
    password: Pasword123#@
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
#  output:
#    ansi:
#      enabled: true
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9000/eureka