server:
  port: 8080
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#      routes:
#        - id: USERS
#          uri: http://localhost:8081/
#          predicates:
#            - Path=/cadastro/**
#        - id: PRODUCT
#          uri: http://localhost:8095/
#          predicates:
#            - Path=/order/**