server:
  port: 8091
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javatos
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Password123#@
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
#  output:
#    ansi:
#      enabled: true
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9000/eureka