server:
  port: 8888
spring:
  application:
    name: config-server

    ##pega direto do git
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/Acelera-G4/e-commerceG4/tree/vscGabriel/config
#          username: vscGabriel
#          password: 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
          ## local
  profiles:
    active: native
  cloud:
    config:
      server:
        git: file://C://Users//a832444//e-commerceG4//e-commerceG4//config
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9000/eureka