server:
  port: 8888
spring:
  application:
    name: config-server

#    ##pega direto do git
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/Acelera-G4/e-commerceG4/tree/main/config
#          skip-ssl-validation: true


   # local
  profiles:
    active: native
  cloud:
    config:
      server:
        git: file://C://Users//a832444//e-commerceG4//e-commerceG4//config
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9001/eureka