server:
  port: 8888
spring:
  application:
    name: config-server

#    ##pega direto do github
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Acelera-G4/config-repo
          search-paths:
            - config
          skipSslValidation: true

#   # local
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        git: file://C://Users//a832444//e-commerceG4//e-commerceG4//config
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:9001/eureka